name: Windows

on: [ push, pull_request ]

jobs:
  build:
    name: MSVC, ${{matrix.os}} (${{matrix.arch}}), ${{matrix.build_type}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, windows-2025-vs2026, windows-11-arm ]
        build_type: [ Debug, Release ]
        include:
          - os: windows-2022
            arch: x64
          - os: windows-2025-vs2026
            arch: x64
          - os: windows-11-arm
            arch: arm64

    steps:
      - uses: actions/checkout@v5

      - name: Set up MSVC environment
        shell: cmd
        env:
          VCVARS_ARCH: ${{ matrix.arch == 'arm64' && 'arm64' || '64' }}
        run: |
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath`) do set VSDIR=%%i
          call "%VSDIR%\VC\Auxiliary\Build\vcvars%VCVARS_ARCH%.bat" || exit /b 1
          set | findstr /R /V "^=" >> "%GITHUB_ENV%"

      - name: Report compiler version
        shell: cmd
        run: cl 2>&1 | findstr Version

      - name: Configure build
        working-directory: ${{runner.workspace}}
        shell: cmd
        run: |
          cmake -Bbuild -S %GITHUB_WORKSPACE% ^
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ^
                -DCMAKE_CXX_STANDARD_REQUIRED=ON ^
                -DCMAKE_CXX_EXTENSIONS=OFF ^
                -DASPARTAME_ENABLE_TEST=ON ^
                -DASPARTAME_ENABLE_BENCHMARK=ON ^
                -G Ninja

      - name: Build tests + lib
        working-directory: ${{runner.workspace}}
        shell: cmd
        run: cmake --build build --target all

      - name: Run CXX20 tests
        working-directory: ${{runner.workspace}}
        shell: cmd
        run: build\test_20.exe

      - name: Run CXX17 tests
        working-directory: ${{runner.workspace}}
        shell: cmd
        run: build\test_17.exe

  example:
    name: example FetchContent
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v5
      - name: Set up MSVC environment
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath`) do set VSDIR=%%i
          call "%VSDIR%\VC\Auxiliary\Build\vcvars64.bat" || exit /b 1
          set | findstr /R /V "^=" >> "%GITHUB_ENV%"
      - name: Configure example
        shell: cmd
        run: cmake -S example -B example/build -G Ninja
      - name: Build example
        shell: cmd
        run: cmake --build example/build
      - name: Run example
        shell: cmd
        run: example\build\example.exe
